clear; close all; clc;

% This script tunes "API_mean" (forced by true rainfall) toward unscaled SM meas.
% If "bb" == -1, also tune bb together with API_mean; otherwise, only tune API_mean

%API_with_true_rain('input_dataset', './input/SMART_input_one_cell_washita_smap_no_winter.mat', ...
tune_API_param('input_dataset', './input/SMART_input_smap_arkansas.mat', ...
      'output_dir', './output', ...
      'start_time', '2015-03-31 00:00', ...
      'end_time', '2017-12-31 21:00', ...
      'time_step', '3', ...
      'filter_flag', '6', ...
      'transform_flag', '1', ...
      'API_model_flag', '0', ...
      'lambda_flag', '999', ...
      'NUMEN', '16', ...
      'Q_fixed', '0.3', ...
      'P_inflation', '0', ...  % 0.04
      'upper_bound_API', '99999', ...
      'logn_var', '1', ...
      'phi', '0.9', ...   % autocorrelation of precip perturbation
      'slope_parameter_API', '0.01', ...
      'location_flag', '1', ...
      'window_size', '1', ...
      'API_mean', '0.98', ...
      'bb', '-1', ...
      'API_range', '0.15', ...
      'sep_sm_orbit', '1', ...
      'synth_meas_error', '0.1');  % synthetic meas. error standard deviation (in the API regime)

%Argument list:
%filter_flag 1)KF, 2)EnKF, 3)DI, 4)PART, 5)KF with RTS gap-filling, 6) EnKF with EnKS gap-filling, 7) PART - DIRECT RAINFALL
%transform_flag 1) CDF, 2) seasonal 1&2, 3) long-term 1&2, 4) seasonal CDF 
%API_model_flag 0) static 1) simple sine model, 2) Ta climatology, 3) PET climatologoy, 4) Ta-variation, 5) PET variation
%lambda_flag - if = 999 then obtain lambda via fitting against
%"rain_indep", otherwise it sets a fixed value of lambda
%NUMEN - number of ensembles used in EnKF or EnKS analysis...not used if filter_flag  = 1 or 3
%Q_fixed - if = 999 than whiten tune, otherwise it sets Q
%P_inflation
%logn_var...variance of multiplicative ensemble perturbations...not sued if filter_flag = 1 or 3....setting to zero means all rainfall error is additive
%slope parameter API - not used if API_model_flag = 0
%location flag 0) CONUS, 1) AMMA, 2) Global 3) Australia 31 4) Australia 240 5) Australia, 0.25-degree continental
%window size - default is one
%API_mean and bb - where API(t) = API_mean*API(t-1)^bb + rain(t)...default is one
%API_range -  %Only used if API is varying seasonally
%sep_sm_orbit - 1 for separately rescaling ascending and descending SM (this
%   only makes sense for subdaily run); 0 for combining ascending and descending
%   soil moisture products and SM obs appearing on the same timestep will
%   be averaged
