clear; close all; clc;

% SMART(6,3,0,999,100,3,5,1,0,0.60,1,1);

SMART('input_dataset', './SMART_Input.mat', ...
      'output_dataset', './SMART_output.mat', ...
      'start_date', '1949-01-01', ... % '2010-01-01', ...
      'end_date', '1949-01-10', ... % '2013-12-31', ...
      'filter_flag', '5', ... % 1, ...
      'transform_flag', '3', ...
      'API_model_flag', '0', ...
      'lambda_flag', '999', ...
      'NUMEN', '100', ...
      'Q_fixed', '3', ...
      'P_inflation', '5', ...
      'upper_bound_API', '99999', ...
      'logn_var', '0', ...
      'slope_parameter_API', '0.01', ...
      'location_flag', '1', ...
      'window_size', '1', ...
      'API_mean', '0.6', ...
      'bb', '1', ...
      'API_range', '0.15');

%Argument list:
%filter_flag 1)KF, 2)EnKF, 3)DI, 4)PART, 5)KF with RTS gap-filling, 6) EnKF with EnKS gap-filling, 7) PART - DIRECT RAINFALL
%transform_flag 1) CDF, 2) seasonal 1&2, 3) long-term 1&2, 4) seasonal CDF 
%API_model_flag 0) static 1) simple sine model, 2) Ta climatology, 3) PET climatologoy, 4) Ta-variation, 5) PET variation
%lambda_flag - if = 999 then obtain lambda via fitting against
%"rain_indep", otherwise it sets a fixed value of lambda
%NUMEN - number of ensembles used in EnKF or EnKS analysis...not used if filter_flag  = 1 or 3
%Q_fixed - if = 999 than whiten tune, otherwise it sets Q
%P_inflation
%logn_var...variance of multiplicative ensemble perturbations...not sued if filter_flag = 1 or 3....setting to zero means all rainfall error is additive
%slope parameter API - not used if API_model_flag = 0
%location flag 0) CONUS, 1) AMMA, 2) Global 3) Australia 31 4) Australia 240 5) Australia, 0.25-degree continental
%window size - default is one
%API_mean and bb - where API(t) = API_mean*API(t-1)^bb + rain(t)...default is one
%API_range -  %Only used if API is varying seasonally