clear; close all; clc;

% SMART(6,3,0,999,100,3,5,1,0,0.60,1,1);

SMART('input_dataset', './SMART_input_arkansas.prec_std_1.mat', ...
      'output_dir', './output', ...
      'start_time', '1980-01-01 00:00', ...
      'end_time', '1980-12-31 21:00', ...
      'time_step', '3', ...
      'filter_flag', '6', ...
      'transform_flag', '4', ...
      'API_model_flag', '0', ...
      'lambda_flag', '999', ...
      'NUMEN', '32', ...
      'Q_fixed', '1', ...
      'P_inflation', '5', ...  % 0.04
      'upper_bound_API', '99999', ...
      'logn_var', '1', ...
      'slope_parameter_API', '0.01', ...
      'location_flag', '1', ...
      'window_size', '24', ...
      'API_mean', '0.6', ...
      'bb', '1', ...
      'API_range', '0.15', ...
      'sep_sm_orbit', '1');

%Argument list:
%filter_flag 1)KF, 2)EnKF, 3)DI, 4)PART, 5)KF with RTS gap-filling, 6) EnKF with EnKS gap-filling, 7) PART - DIRECT RAINFALL
%transform_flag 1) CDF, 2) seasonal 1&2, 3) long-term 1&2, 4) seasonal CDF 
%API_model_flag 0) static 1) simple sine model, 2) Ta climatology, 3) PET climatologoy, 4) Ta-variation, 5) PET variation
%lambda_flag - if = 999 then obtain lambda via fitting against
%"rain_indep", otherwise it sets a fixed value of lambda
%NUMEN - number of ensembles used in EnKF or EnKS analysis...not used if filter_flag  = 1 or 3
%Q_fixed - if = 999 than whiten tune, otherwise it sets Q
%P_inflation
%logn_var...variance of multiplicative ensemble perturbations...not sued if filter_flag = 1 or 3....setting to zero means all rainfall error is additive
%slope parameter API - not used if API_model_flag = 0
%location flag 0) CONUS, 1) AMMA, 2) Global 3) Australia 31 4) Australia 240 5) Australia, 0.25-degree continental
%window size - default is one
%API_mean and bb - where API(t) = API_mean*API(t-1)^bb + rain(t)...default is one
%API_range -  %Only used if API is varying seasonally
%sep_sm_orbit - 1 for separately rescaling ascending and descending SM (this
%   only makes sense for subdaily run); 0 for combining ascending and descending
%   soil moisture products and SM obs appearing on the same timestep will
%   be averaged